### ISSUE TITLE
Video Duration issue

### ISSUE THREAD

**Issue by ehsanali1992** [art-mironoff/react-video-markers#5]
![image](https://user-images.githubusercontent.com/45037292/75780287-ddfe9b80-5d7c-11ea-83a1-4cd86c44882a.png)
 Video duration showing NaN

**Comment by art-mironoff** [comment]
Hi, could you send me link to this video. I can`t reproduce this bug without it.

**Comment by ehsanali1992** [comment]
Please check your email, can't share link here due to security reasons

**Comment by art-mironoff** [comment]
Please check again. I think I fixed this bug.

**Comment by ehsanali1992** [comment]
The problem is still there. It is displaying Nan at first for few seconds, after that it displays duration.

**Comment by art-mironoff** [comment]
I can’t reproduce this error anymore. I emulated slow internet and only see 00:00/00:00 at first few seconds.
